# Deep Continuous Bag of Words

![alt text](src/arch.jpg)

source: https://people.cs.umass.edu/~miyyer/pubs/2015_acl_dan.pdf

In [52]:
# Import necessary modules

import numpy as np
import pandas as pd
import re

from tqdm import tqdm
import random

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torch.utils.data as data_utils

In [2]:
# Create word2vec dictionary

def load_word_vectors(filename):
    word_to_index = {}
    word_vectors  = []
    
    with open(filename, encoding="utf8") as fp:
        for line in tqdm(fp.readlines(), leave = False):
            line = line.split(" ")
            
            word = line[0]
            word_to_index[word] = len(word_to_index)
            
            vec = np.array([float(x) for x in line[1:]])
            word_vectors.append(vec)
            
    return word_to_index, word_vectors

word_to_index, word_vectors = load_word_vectors("model/glove.6B.100d.txt")

In [3]:
# Import csv file of amazon reviews

df = pd.read_csv("data/amazon_reviews_small.csv", names = ['sentiment', 'title', 'content'])
df.head()

sentiment                         title  \
0          2            Right on the money   
1          2           Serves its Purpose!   
2          2         Trailer Park Bwoys!!!   
3          1                  buyer beware   
4          2  Great for those cold winters   

                                             content  
0  We are using the this book to get 100+ certifi...  
1  Couldn't go without it. My 3 1/2 year still we...  
2  we get to see it on paramount in ol' LND UK an...  
3  There are companies selling Bosch knock-offs o...  
4  If you are looking to keep your water liquifie...

In [4]:
def get_vectors(phrase):
    phrase = phrase.split(' ')
    vector = np.zeros((1,100))
    word_count = 0
    for word in phrase:
        try:
            vector += np.asarray(word_vectors[word_to_index[word]])
            word_count += 1
        except:
            pass
    
    if word_count > 0:
        ans = vector/word_count
    else:
        ans = np.zeros((1,100))
    
    return ans
    
def clean_phrase(phrase):
    phrase = phrase.lower()
    phrase = phrase.replace("'", "")
    phrase = phrase.replace(".", "")
    phrase = re.sub(r'([^\s\w]|_)+', '', phrase)
    return phrase

def generate_phrases(dataset):
    phrases = dataset[['title', 'content']].dropna().values.flatten().tolist()
    return phrases
    
def generate_tfidf(phrases):
    tfidf = TfidfVectorizer()
    tfidf.fit(phrases)
    return tfidf

def phrase_cbow(a, b):
    aa = a.reshape(1,-1)
    ba = b.reshape(1,-1)
    
    cos_lib = cosine_similarity(aa, ba)

    return cos_lib

In [5]:
df['sentiment']     = [(a-1) for a in df.sentiment.values]
df['title_clean']   = [clean_phrase(str(a)) for a in df.title]
df['content_clean'] = [clean_phrase(str(a)) for a in df.content]

In [6]:
tfidf = generate_tfidf(generate_phrases(df))

In [7]:
print("Generating clean title")
df['title_rep']     = [tfidf.transform([a]) for a in df.title_clean]
print("Generating clean content")
df['content_rep']   = [tfidf.transform([a]) for a in df.content_clean]

Generating clean title
Generating clean content


In [8]:
print("Generating clean title vector")
df['title_vec']     = [get_vectors(a) for a in df.title_clean]
print("Generating clean content vector")
df['content_vec']   = [get_vectors(a) for a in df.content_clean]

Generating clean title vector
Generating clean content vector


In [9]:
df['cosine']        = [phrase_cbow(get_vectors(a), get_vectors(b)) for a,b in zip(df.title_clean, df.content_clean)]

In [10]:
df['feature'] = [np.hstack((a,b,c)).reshape(1,-1) for a,b,c in df[['title_vec', 'content_vec', 'cosine']].values]

In [11]:
df_set = df.drop(columns = ['title_clean', 'content_clean', 'title_rep', 'content_rep', 'title_vec', 'content_vec', 'cosine'])
df_set.head()

sentiment                         title  \
0          1            Right on the money   
1          1           Serves its Purpose!   
2          1         Trailer Park Bwoys!!!   
3          0                  buyer beware   
4          1  Great for those cold winters   

                                             content  \
0  We are using the this book to get 100+ certifi...   
1  Couldn't go without it. My 3 1/2 year still we...   
2  we get to see it on paramount in ol' LND UK an...   
3  There are companies selling Bosch knock-offs o...   
4  If you are looking to keep your water liquifie...   

                                             feature  
0  [[0.11201899999999998, 0.03991249999999999, 0....  
1  [[-0.08785333333333334, -0.022782999999999998,...  
2  [[0.23044, -0.04867500000000001, 0.431965, -0....  
3  [[0.10213000000000001, 0.18035, 0.790140000000...  
4  [[-0.3699188, 0.3999688, 0.37708379999999997, ...

In [132]:
pos_sent = df.loc[df['sentiment'] == 1]
neg_sent = df.loc[df['sentiment'] != 1]

pos_sent['sentiment'] = [[0, 1] for a in pos_sent['sentiment'].values]
neg_sent['sentiment'] = [[1, 0] for a in neg_sent['sentiment'].values]

pos_temp = pos_sent.sample(frac = 1)
neg_temp = neg_sent.sample(frac = 1)

pos_points = len(pos_temp)
neg_points = len(neg_temp)

train_pos = pos_temp.iloc[:int(pos_points*.7)]
train_neg = neg_temp.iloc[:int(neg_points*.7)]
train     = pd.concat([train_pos, train_neg])

valid_pos = pos_temp.iloc[int(pos_points*.7):int(pos_points*.85)]
valid_neg = neg_temp.iloc[int(neg_points*.7):int(neg_points*.85)]
valid     = pd.concat([valid_pos, valid_neg])

test_pos  = pos_temp.iloc[int(pos_points*.85):]
test_neg  = neg_temp.iloc[int(neg_points*.85):]
test      = pd.concat([test_pos, test_neg])

#pd.concat([a, b])

D:\Users\Prince\Anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
D:\Users\Prince\Anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


In [13]:
np.concatenate(np.asarray(train.feature.values))

array([[-2.72975000e-01,  2.08066500e-01,  2.04910000e-01, ...,
         4.70023125e-01,  3.13645115e-01,  8.06552182e-01],
       [ 7.60000000e-04,  7.40733333e-02,  5.50811167e-01, ...,
         3.74438457e-01,  2.44254436e-01,  8.97158113e-01],
       [ 2.03083333e-02,  3.86762000e-01,  3.46700000e-01, ...,
         6.08676554e-01,  2.32992838e-01,  8.81940123e-01],
       ...,
       [-1.00409692e-01,  1.78799077e-01,  4.53550385e-01, ...,
         2.67125359e-01,  3.42334231e-01,  9.69899721e-01],
       [-3.09985000e-01, -8.03162500e-02,  5.36435000e-04, ...,
         5.25560185e-01,  7.80769778e-02,  8.80850007e-01],
       [-1.07940000e-02, -2.61457500e-02,  4.28662500e-01, ...,
         5.14350984e-01,  9.80330588e-02,  7.30414923e-01]])

In [14]:
train_tensor = data_utils.TensorDataset(torch.tensor(np.concatenate(np.asarray(train.feature.values), axis = 0)).float(), 
                                        torch.tensor(np.vstack(train.sentiment.values)))
valid_tensor = data_utils.TensorDataset(torch.tensor(np.concatenate(np.asarray(valid.feature.values), axis = 0)).float(), 
                                        torch.tensor(np.vstack(valid.sentiment.values)))
test_tensor  = data_utils.TensorDataset(torch.tensor(np.concatenate(np.asarray(test.feature.values), axis = 0)).float(), 
                                        torch.tensor(np.vstack(test.sentiment.values)))

In [15]:
batch_size = 32

train_loader = data_utils.DataLoader(train_tensor, batch_size = batch_size, shuffle = True)
valid_loader = data_utils.DataLoader(valid_tensor, batch_size = batch_size, shuffle = True)
test_loader = data_utils.DataLoader(test_tensor, batch_size = batch_size, shuffle = True)

In [16]:
train_on_gpu = torch.cuda.is_available()

model = nn.Sequential(nn.Linear(201, 100),
                      nn.ReLU(),
                      nn.Linear(100, 50),
                      nn.ReLU(),
                      nn.Linear(50, 2),
                      nn.Softmax(dim=1))

if train_on_gpu:
    model.cuda()

criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.03)

In [17]:
epochs = 10
valid_min = np.Inf
for e in range(epochs):
    running_loss_train = 0
    model.train
    for features, labels in train_loader:
        if train_on_gpu:
            features, labels = features.cuda(), labels.cuda()
        optimizer.zero_grad()
        output = model(features)
        loss = criterion(output, labels.float())
        loss.backward()
        optimizer.step()
        
        running_loss_train += loss.item()

        
    running_loss_valid = 0
    model.eval
    for features, labels in train_loader:
        if train_on_gpu:
            features, labels = features.cuda(), labels.cuda()
        output = model(features)
        loss = criterion(output, labels.float())
        
        running_loss_valid += loss.item()

        
    print(f"Epoch {e}    Training loss: {running_loss_train/len(train_loader):.6f}\tValidation loss: {running_loss_valid/len(train_loader):.6f}")
    
    if running_loss_valid < valid_min:
        print("Validation loss decreased. Saving model...")
        torch.save(model.state_dict(), 'model.pt')
        valid_min = running_loss_valid

Epoch 0    Training loss: 0.504370	Validation loss: 0.490477
Validation loss decreased. Saving model...
Epoch 1    Training loss: 0.421807	Validation loss: 0.393432
Validation loss decreased. Saving model...
Epoch 2    Training loss: 0.403042	Validation loss: 0.381404
Validation loss decreased. Saving model...
Epoch 3    Training loss: 0.392264	Validation loss: 0.372416
Validation loss decreased. Saving model...
Epoch 4    Training loss: 0.380691	Validation loss: 0.359096
Validation loss decreased. Saving model...
Epoch 5    Training loss: 0.371665	Validation loss: 0.412038
Epoch 6    Training loss: 0.365496	Validation loss: 0.347995
Validation loss decreased. Saving model...
Epoch 7    Training loss: 0.359001	Validation loss: 0.355871
Epoch 8    Training loss: 0.352776	Validation loss: 0.347332
Validation loss decreased. Saving model...
Epoch 9    Training loss: 0.348699	Validation loss: 0.375379


In [28]:
test_loss = 0.0
model.eval

model.load_state_dict(torch.load('model.pt'))

correct = 0
total = 0

model.cuda()

for features, labels in test_loader:
    if train_on_gpu:
        features, labels = features.cuda(), labels.cuda()
    output = model(features)
    print(output, labels)
    _, pred = torch.max(output, 1)
    _, true = torch.max(labels, 1)
    loss = criterion(output, labels.float())
    test_loss += loss.item()
    for a, b in zip(pred, true):
        if a.item() == b.item():
            correct += 1
        total += 1

print(f"Model test loss is {test_loss/len(test_loader):.6f}.")
print(f"Model got {correct} out of {total} correct.")
print(f"Model test accuracy: {correct*100/total:.2f}%")

tensor([[0.0281, 0.9719],
        [0.9143, 0.0857],
        [0.9549, 0.0451],
        [0.0204, 0.9796],
        [0.9851, 0.0149],
        [0.9971, 0.0029],
        [0.9959, 0.0041],
        [0.9190, 0.0810],
        [0.9348, 0.0652],
        [0.0230, 0.9770],
        [0.4016, 0.5984],
        [0.9138, 0.0862],
        [0.0228, 0.9772],
        [0.1601, 0.8399],
        [0.9214, 0.0786],
        [0.9339, 0.0661],
        [0.9578, 0.0422],
        [0.9623, 0.0377],
        [0.0025, 0.9975],
        [0.9506, 0.0494],
        [0.0431, 0.9569],
        [0.0972, 0.9028],
        [0.0167, 0.9833],
        [0.6669, 0.3331],
        [0.2463, 0.7537],
        [0.9109, 0.0891],
        [0.8822, 0.1178],
        [0.8692, 0.1308],
        [0.0733, 0.9267],
        [0.9682, 0.0318],
        [0.3944, 0.6056],
        [0.9961, 0.0039]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1,

        [8.2839e-01, 1.7161e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[8.5264e-01, 1.4736e-01],
        [1.1572e-01, 8.8428e-01],
        [1.5073e-01, 8.4927e-01],
        [9.8315e-02, 9.0168e-01],
        [9.5574e-01, 4.4256e-02],
        [3.6938e-01, 6.3062e-01],
        [1.1151e-01, 8.8849e-01],
        [4.3913e-01, 5.6087e-01],
        [7.5969e-01, 2.4031e-01],
        [9.8908e-01, 1.0923e-02],
        [9.1698e-01, 8.3020e-02]

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[1.6303e-01, 8.3697e-01],
        [6.5958e-01, 3.4042e-01],
        [4.6025e-02, 9.5398e-01],
        [7.5804e-01, 2.4196e-01],
        [5.6178e-01, 4.3822e-01],
        [9.1329e-01, 8.6714e-02],
        [7.0027e-01, 2.9973e-01],
        [2.9164e-01, 7.0836e-01],
        [9.1180e-01, 8.8199e-02],
        [1.4081e-01, 8.5919e-01],
        [2.8728e-01, 7.1272e-01],
        [9.3336e-01, 6.6642e-02],
        [4.6703e-03, 9.9533e-01],
        [9.4286e-01, 5.7144e-02],
        [5.2149e-02, 9.4785e-01],
        [9.6509e-01, 3.4905e-02],
        [2.6275e-02, 9.7373e-01],
        [2.3016e-02, 9.7698e-01],
        [2.7744e-02, 9.7226e-01],
        [8.5008e-01, 1.4992e-01],
        [6.5562e-01, 3.4438e-01],
        [7.4129e-03, 9.9259e-01],
        [6.4790e-01, 3.5210e-01],
        [2.0231e-01, 7.9769e-01],
        [6.1093e-02, 9.3891e-01],
        [9.6836e-01, 3.1639e-02],
        [9.9940e-01, 6.0159e-04],
        [4.4358e-01, 5.5642e-

        [9.9659e-01, 3.4070e-03]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.9948, 0.0052],
        [0.7166, 0.2834],
        [0.9453, 0.0547],
        [0.3892, 0.6108],
        [0.5778, 0.4222],
        [0.9268, 0.0732],
        [0.0480, 0.9520],
        [0.4906, 0.5094],
        [0.3122, 0.6878],
        [0.4781, 0.5219],
        [0.7905, 0.2095],
        [0.9531, 0.0469],
        [0.8785, 0.1215],
        [0.3178, 0.6822],
        

        [1.2369e-02, 9.8763e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.3658, 0.6342],
        [0.7853, 0.2147],
        [0.9391, 0.0609],
        [0.9328, 0.0672],
        [0.8095, 0.1905],
        [0.7089, 0.2911],
        [0.0136, 0.9864],
        [0.9942, 0.0058],
        [0.7054, 0.2946],
        [0.5434, 0.4566],
        [0.5961, 0.4039],
        [0.8571, 0.1429],
        [0.0481, 0.9519],
        [0.9892, 0.0108],
        

        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.9929, 0.0071],
        [0.8566, 0.1434],
        [0.9798, 0.0202],
        [0.7137, 0.2863],
        [0.9955, 0.0045],
        [0.8559, 0.1441],
        [0.0915, 0.9085],
        [0.9515, 0.0485],
        [0.9757, 0.0243],
        [0.1236, 0.8764],
        [0.4146, 0.5854],
        [0.7598, 0.2402],
        [0.0301, 0.9699],
        [0.6372, 0.3628],
        [0.7349, 0.2651],
        [0.2625, 0.7375],
        [0.0246, 0.9754],
        [0.3425, 0.6575],
        [0.9575, 0.0425],
        [0.8084, 0.1916],
        [0.0514, 0.9486],
        [0.7149, 0.2851],
        [0.1044, 0.8956],
        [0.9944, 0.0056],
        [0.7221, 0.2779],
        [0.2103, 0.7897],
        [0.5413, 0.4587],
        [0.9184, 0.0816],
        [0.0052, 0.9948],
        [0.8934, 0.1066],
        [0.1398, 0.8602],
        [0.6997, 0.3003]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
      

        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.0881, 0.9119],
        [0.0063, 0.9937],
        [0.8385, 0.1615],
        [0.9607, 0.0393],
        [0.6373, 0.3627],
        [0.0295, 0.9705],
        [0.9841, 0.0159],
        [0.1500, 0.8500],
        [0.9667, 0.0333],
        [0.2105, 0.7895],
        [0.0116, 0.9884],
        [0.8789, 0.1211],
        [0.7863, 0.2137],
        [0.9016, 0.0984],
        [0.8053, 0.1947],
        [0.9812, 0.0188],
        [0.9981, 0.0019],
        [0.0155, 0.9845],
        [0.6778, 0.3222],
        [0.1617, 0.8383],
        [0.0045, 0.9955],
        [0.8710, 0.1290],
        [0.9833, 0.0167],
        [0.9679, 0.0321],
        [0.8489, 0.1511],
        [0.5174, 0.4826],
        [0.8483, 0.1517],
        [0.0228, 0.9772],
        [0.2681, 0.7319],
        [0.0044, 0.9956],
        [0.3822, 0.6178],
        [0.6598, 0.3402]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
      

        [6.5989e-02, 9.3401e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[7.9913e-01, 2.0087e-01],
        [9.9489e-01, 5.1053e-03],
        [6.9756e-01, 3.0244e-01],
        [3.7774e-02, 9.6223e-01],
        [8.8055e-02, 9.1195e-01],
        [2.6099e-02, 9.7390e-01],
        [2.1297e-01, 7.8703e-01],
        [8.4469e-02, 9.1553e-01],
        [3.0630e-02, 9.6937e-01],
        [9.9969e-01, 3.0545e-04],
        [4.6570e-01, 5.3430e-01]

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[1.6955e-01, 8.3045e-01],
        [9.9825e-02, 9.0017e-01],
        [4.9554e-01, 5.0446e-01],
        [8.2945e-01, 1.7055e-01],
        [9.7094e-01, 2.9061e-02],
        [9.6495e-01, 3.5054e-02],
        [2.4461e-02, 9.7554e-01],
        [5.6461e-02, 9.4354e-01],
        [9.5061e-01, 4.9387e-02],
        [1.2532e-03, 9.9875e-01],
        [5.2963e-01, 4.7037e-01],
        [8.8034e-01, 1.1966e-01],
        [6.6908e-02, 9.3309e-01],
        [2.4343e-03, 9.9757e-01],
        [9.3358e-01, 6.6416e-02],
        [4.6430e-03, 9.9536e-01],
        [9.2407e-04, 9.9908e-01],
        [9.8167e-01, 1.8331e-02],
        [9.7298e-01, 2.7016e-02],
        [3.1704e-02, 9.6830e-01],
        [9.3255e-01, 6.7449e-02],
        [9.6330e-01, 3.6700e-02],
        [9.9236e-01, 7.6399e-03],
        [3.7314e-03, 9.9627e-01],
        [9.3463e-01, 6.5367e-02],
        [3.5362e-02, 9.6464e-01],
        [8.3769e-02, 9.1623e-01],
        [9.9915e-01, 8.4678e-

        [3.0162e-02, 9.6984e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.1676, 0.8324],
        [0.0045, 0.9955],
        [0.9170, 0.0830],
        [0.9008, 0.0992],
        [0.0130, 0.9870],
        [0.8993, 0.1007],
        [0.1437, 0.8563],
        [0.7004, 0.2996],
        [0.0303, 0.9697],
        [0.9678, 0.0322],
        [0.0259, 0.9741],
        [0.0305, 0.9695],
        [0.7048, 0.2952],
        [0.0726, 0.9274],
        

        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.9644, 0.0356],
        [0.9224, 0.0776],
        [0.3247, 0.6753],
        [0.0509, 0.9491],
        [0.9066, 0.0934],
        [0.7079, 0.2921],
        [0.0135, 0.9865],
        [0.9398, 0.0602],
        [0.4782, 0.5218],
        [0.9619, 0.0381],
        [0.9326, 0.0674],
        [0.7468, 0.2532],
        [0.9463, 0.0537],
        [0.9808, 0.0192],
        [0.3599, 0.6401],
        [0.9640, 0.0360],
        [0.0348, 0.9652],
        [0.8404, 0.1596],
        [0.6697, 0.3303],
        [0.7007, 0.2993],
        [0.8683, 0.1317],
        [0.8793, 0.1207],
        [0.0024, 0.9976],
        [0.9923, 0.0077],
        [0.3870, 0.6130],
        [0.7084, 0.2916],
        [0.0081, 0.9919],
        [0.0243, 0.9757],
        [0.8982, 0.1018],
        [0.0100, 0.9900],
        [0.0121, 0.9879],
        [0.9987, 0.0013]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
      

        [0.9207, 0.0793]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.1689, 0.8311],
        [0.3397, 0.6603],
        [0.0750, 0.9250],
        [0.0750, 0.9250],
        [0.0272, 0.9728],
        [0.9827, 0.0173],
        [0.0805, 0.9195],
        [0.0254, 0.9746],
        [0.9363, 0.0637],
        [0.9580, 0.0420],
        [0.0924, 0.9076],
        [0.0084, 0.9916],
        [0.5536, 0.4464],
        [0.2631, 0.7369],
        [0.8694,

        [0.0418, 0.9582]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.0383, 0.9617],
        [0.5153, 0.4847],
        [0.1288, 0.8712],
        [0.9617, 0.0383],
        [0.9171, 0.0829],
        [0.9669, 0.0331],
        [0.2206, 0.7794],
        [0.8537, 0.1463],
        [0.8843, 0.1157],
        [0.1808, 0.8192],
        [0.0839, 0.9161],
        [0.9925, 0.0075],
        [0.9673, 0.0327],
        [0.0148, 0.9852],
        [0.8835,

        [9.9082e-01, 9.1835e-03]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.3327, 0.6673],
        [0.2433, 0.7567],
        [0.9360, 0.0640],
        [0.9001, 0.0999],
        [0.6664, 0.3336],
        [0.7385, 0.2615],
        [0.0187, 0.9813],
        [0.6028, 0.3972],
        [0.0079, 0.9921],
        [0.0415, 0.9585],
        [0.0194, 0.9806],
        [0.9269, 0.0731],
        [0.0156, 0.9844],
        [0.9515, 0.0485],
        

        [5.7700e-01, 4.2300e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.4526, 0.5474],
        [0.0215, 0.9785],
        [0.0093, 0.9907],
        [0.0842, 0.9158],
        [0.0380, 0.9620],
        [0.7433, 0.2567],
        [0.8097, 0.1903],
        [0.4306, 0.5694],
        [0.8323, 0.1677],
        [0.3181, 0.6819],
        [0.8230, 0.1770],
        [0.0166, 0.9834],
        [0.9569, 0.0431],
        [0.9933, 0.0067],
        

        [0.9863, 0.0137]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.1200, 0.8800],
        [0.2118, 0.7882],
        [0.8784, 0.1216],
        [0.0031, 0.9969],
        [0.8637, 0.1363],
        [0.8509, 0.1491],
        [0.9505, 0.0495],
        [0.9907, 0.0093],
        [0.0216, 0.9784],
        [0.9393, 0.0607],
        [0.9801, 0.0199],
        [0.0547, 0.9453],
        [0.9102, 0.0898],
        [0.9759, 0.0241],
        [0.0402,

        [3.6254e-01, 6.3746e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.3668, 0.6332],
        [0.9460, 0.0540],
        [0.8253, 0.1747],
        [0.9602, 0.0398],
        [0.8069, 0.1931],
        [0.8637, 0.1363],
        [0.0606, 0.9394],
        [0.8963, 0.1037],
        [0.0678, 0.9322],
        [0.0106, 0.9894],
        [0.0701, 0.9299],
        [0.9879, 0.0121],
        [0.2143, 0.7857],
        [0.7441, 0.2559],
        

        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[8.5040e-01, 1.4960e-01],
        [6.6764e-04, 9.9933e-01],
        [2.9304e-01, 7.0696e-01],
        [7.7899e-01, 2.2101e-01],
        [8.1408e-01, 1.8592e-01],
        [9.7596e-01, 2.4037e-02],
        [2.0138e-01, 7.9862e-01],
        [1.6446e-01, 8.3554e-01],
        [5.8265e-01, 4.1735e-01],
        [4.1843e-01, 5.8157e-01],
        [9.7057e-01, 2.9434e-02],
        [9.5489e-01, 4.5106e-02],
        [5.0193e-01, 4.9807e-01],
        [9.5713e-01, 4.2868e-02],
        [5.3673e-01, 4.6327e-01],
        [8.3759e-01, 1.6241e-01],
        [7.7104e-01, 2.2896e-01],
        [8.2697e-01, 1.7303e-01],
        [4.7525e-02, 9.5247e-01],
        [3.1017e-02, 9.6898e-01],
        [9.7280e-01, 2.7198e-02],
        [8.7983e-01, 1.2017e-01],
        [9.2057e-01, 7.9435e-02],
        [1.3358e-02, 9.8664e-01],
        [1.4268e-02, 9.8573e-01],
        [1.0975e-02, 9.8903e-01],
        [7.1370e-01, 2.8630e-01],
        [8.4046e-01, 1.5954e-

        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.1536, 0.8464],
        [0.5404, 0.4596],
        [0.2259, 0.7741],
        [0.7661, 0.2339],
        [0.0424, 0.9576],
        [0.8765, 0.1235],
        [0.2885, 0.7115],
        [0.7940, 0.2060],
        [0.9839, 0.0161],
        [0.0023, 0.9977],
        [0.4339, 0.5661],
        [0.9674, 0.0326],
        [0.9942, 0.0058],
        [0.9741, 0.0259],
        [0.9132, 0.0868],
        [0.0273, 0.9727],
        [0.3072, 0.6928],
        [0.2440, 0.7560],
        [0.6819, 0.3181],
        [0.6416, 0.3584],
        [0.9935, 0.0065],
        [0.9553, 0.0447],
        [0.0098, 0.9902],
        [0.8329, 0.1671],
        [0.0112, 0.9888],
        [0.0032, 0.9968],
        [0.2666, 0.7334],
        [0.0549, 0.9451],
        [0.7717, 0.2283],
        [0.5664, 0.4336],
        [0.9481, 0.0519],
        [0.9769, 0.0231]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
      

        [0.3177, 0.6823]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[6.1210e-01, 3.8790e-01],
        [1.8733e-02, 9.8127e-01],
        [6.2858e-01, 3.7142e-01],
        [9.9457e-01, 5.4316e-03],
        [1.0657e-01, 8.9343e-01],
        [9.1434e-01, 8.5657e-02],
        [2.5233e-01, 7.4767e-01],
        [1.8074e-02, 9.8193e-01],
        [9.9969e-01, 3.0843e-04],
        [4.4143e-01, 5.5857e-01],
        [8.8457e-01, 1.1543e-01],
      

        [6.2362e-01, 3.7638e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.0617, 0.9383],
        [0.1583, 0.8417],
        [0.0149, 0.9851],
        [0.4238, 0.5762],
        [0.9840, 0.0160],
        [0.0756, 0.9244],
        [0.0066, 0.9934],
        [0.1967, 0.8033],
        [0.8172, 0.1828],
        [0.2269, 0.7731],
        [0.9211, 0.0789],
        [0.6444, 0.3556],
        [0.6006, 0.3994],
        [0.5858, 0.4142],
        

        [6.6408e-01, 3.3592e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.8851, 0.1149],
        [0.0929, 0.9071],
        [0.9905, 0.0095],
        [0.0285, 0.9715],
        [0.9517, 0.0483],
        [0.3923, 0.6077],
        [0.7264, 0.2736],
        [0.6626, 0.3374],
        [0.9589, 0.0411],
        [0.0299, 0.9701],
        [0.8516, 0.1484],
        [0.0061, 0.9939],
        [0.6393, 0.3607],
        [0.8911, 0.1089],
        

        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.9237, 0.0763],
        [0.7401, 0.2599],
        [0.2479, 0.7521],
        [0.9973, 0.0027],
        [0.9318, 0.0682],
        [0.9685, 0.0315],
        [0.9932, 0.0068],
        [0.5137, 0.4863],
        [0.0314, 0.9686],
        [0.2645, 0.7355],
        [0.0440, 0.9560],
        [0.8459, 0.1541],
        [0.9742, 0.0258],
        [0.9054, 0.0946],
        [0.5850, 0.4150],
        [0.9324, 0.0676],
        [0.2656, 0.7344],
        [0.0433, 0.9567],
        [0.8507, 0.1493],
        [0.0030, 0.9970],
        [0.9910, 0.0090],
        [0.6232, 0.3768],
        [0.0993, 0.9007],
        [0.3663, 0.6337],
        [0.1571, 0.8429],
        [0.1058, 0.8942],
        [0.3256, 0.6744],
        [0.0443, 0.9557],
        [0.9254, 0.0746],
        [0.9878, 0.0122],
        [0.0643, 0.9357],
        [0.9752, 0.0248]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
      

        [0.8420, 0.1580]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.5341, 0.4659],
        [0.0014, 0.9986],
        [0.3739, 0.6261],
        [0.0030, 0.9970],
        [0.6314, 0.3686],
        [0.0082, 0.9918],
        [0.7117, 0.2883],
        [0.9735, 0.0265],
        [0.0568, 0.9432],
        [0.9056, 0.0944],
        [0.9936, 0.0064],
        [0.1051, 0.8949],
        [0.0058, 0.9942],
        [0.2336, 0.7664],
        [0.9968,

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.8436, 0.1564],
        [0.0826, 0.9174],
        [0.9050, 0.0950],
        [0.8955, 0.1045],
        [0.6241, 0.3759],
        [0.0173, 0.9827],
        [0.2714, 0.7286],
        [0.1643, 0.8357],
        [0.9981, 0.0019],
        [0.9112, 0.0888],
        [0.3895, 0.6105],
        [0.0729, 0.9271],
        [0.5517, 0.4483],
        [0.0040, 0.9960],
        [0.9405, 0.0595],
        [0.3866, 0.6134],
        [0.1320, 0.8680],
        [0.0048, 0.9952],
        [0.2586, 0.7414],
        [0.0056, 0.9944],
        [0.9837, 0.0163],
        [0.9910, 0.0090],
        [0.0047, 0.9953],
        [0.4076, 0.5924],
        [0.9856, 0.0144],
        [0.9893, 0.0107],
        [0.0141, 0.9859],
        [0.9673, 0.0327],
        [0.0148, 0.9852],
        [0.2973, 0.7027],
        [0.0133, 0.9867],
        [0.9679, 0.0321]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
      

        [9.4426e-01, 5.5740e-02]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[9.0135e-01, 9.8648e-02],
        [1.0724e-01, 8.9276e-01],
        [2.5217e-01, 7.4783e-01],
        [9.9757e-01, 2.4349e-03],
        [1.1579e-01, 8.8421e-01],
        [9.1435e-01, 8.5650e-02],
        [3.0894e-01, 6.9106e-01],
        [6.9934e-01, 3.0066e-01],
        [5.8776e-01, 4.1224e-01],
        [9.4047e-03, 9.9060e-01],
        [9.8748e-02, 9.0125e-01]

        [9.3751e-01, 6.2485e-02]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.0290, 0.9710],
        [0.7802, 0.2198],
        [0.0057, 0.9943],
        [0.8383, 0.1617],
        [0.8638, 0.1362],
        [0.0553, 0.9447],
        [0.0186, 0.9814],
        [0.9902, 0.0098],
        [0.3854, 0.6146],
        [0.0465, 0.9535],
        [0.1106, 0.8894],
        [0.9728, 0.0272],
        [0.9341, 0.0659],
        [0.9716, 0.0284],
        

        [0.9849, 0.0151]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[9.6324e-01, 3.6759e-02],
        [9.7085e-02, 9.0292e-01],
        [2.7280e-01, 7.2720e-01],
        [1.6699e-01, 8.3301e-01],
        [6.7652e-01, 3.2348e-01],
        [4.4988e-01, 5.5012e-01],
        [5.9410e-01, 4.0590e-01],
        [6.6690e-01, 3.3310e-01],
        [9.4568e-01, 5.4317e-02],
        [7.3760e-01, 2.6240e-01],
        [7.2299e-01, 2.7701e-01],
      

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[4.9687e-01, 5.0313e-01],
        [9.8048e-01, 1.9522e-02],
        [6.8430e-03, 9.9316e-01],
        [9.2401e-01, 7.5993e-02],
        [4.5662e-01, 5.4338e-01],
        [8.7560e-01, 1.2440e-01],
        [6.8757e-01, 3.1243e-01],
        [9.7186e-01, 2.8136e-02],
        [6.2743e-01, 3.7257e-01],
        [9.6457e-01, 3.5429e-02],
        [1.2171e-01, 8.7829e-01],
        [7.0941e-01, 2.9059e-01],
        [8.3816e-01, 1.6184e-01],
        [8.3175e-01, 1.6825e-01],
        [1.2369e-01, 8.7631e-01],
        [7.4545e-01, 2.5455e-01],
        [5.0951e-04, 9.9949e-01],
        [9.1827e-01, 8.1734e-02],
        [4.7544e-01, 5.2456e-01],
        [3.7031e-02, 9.6297e-01],
        [8.9597e-01, 1.0403e-01],
        [1.4472e-02, 9.8553e-01],
        [3.3658e-02, 9.6634e-01],
        [7.0992e-01, 2.9008e-01],
        [5.9538e-03, 9.9405e-01],
        [9.5790e-01, 4.2096e-02],
        [5.3890e-02, 9.4611e-01],
        [9.3889e-01, 6.1108e-

        [7.1971e-01, 2.8029e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.4794, 0.5206],
        [0.9784, 0.0216],
        [0.9448, 0.0552],
        [0.0143, 0.9857],
        [0.5566, 0.4434],
        [0.8628, 0.1372],
        [0.8068, 0.1932],
        [0.9950, 0.0050],
        [0.9223, 0.0777],
        [0.0998, 0.9002],
        [0.4461, 0.5539],
        [0.7657, 0.2343],
        [0.9804, 0.0196],
        [0.9252, 0.0748],
        

        [6.7427e-01, 3.2573e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.9984, 0.0016],
        [0.9941, 0.0059],
        [0.0079, 0.9921],
        [0.3279, 0.6721],
        [0.0011, 0.9989],
        [0.9466, 0.0534],
        [0.9459, 0.0541],
        [0.0015, 0.9985],
        [0.4837, 0.5163],
        [0.9382, 0.0618],
        [0.8246, 0.1754],
        [0.1802, 0.8198],
        [0.9608, 0.0392],
        [0.9544, 0.0456],
        

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.0444, 0.9556],
        [0.9443, 0.0557],
        [0.0571, 0.9429],
        [0.5390, 0.4610],
        [0.4075, 0.5925],
        [0.0766, 0.9234],
        [0.9685, 0.0315],
        [0.0044, 0.9956],
        [0.0064, 0.9936],
        [0.9921, 0.0079],
        [0.9023, 0.0977],
        [0.9770, 0.0230],
        [0.8922, 0.1078],
        [0.6548, 0.3452],
        [0.0912, 0.9088],
        [0.0308, 0.9692],
        [0.7311, 0.2689],
        [0.0110, 0.9890],
        [0.8971, 0.1029],
        [0.9582, 0.0418],
        [0.2015, 0.7985],
        [0.9376, 0.0624],
        [0.9571, 0.0429],
        [0.6264, 0.3736],
        [0.7589, 0.2411],
        [0.2122, 0.7878],
        [0.1827, 0.8173],
        [0.0143, 0.9857],
        [0.1290, 0.8710],
        [0.8966, 0.1034],
        [0.9254, 0.0746],
        [0.6829, 0.3171]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
      

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.1132, 0.8868],
        [0.7886, 0.2114],
        [0.9963, 0.0037],
        [0.7492, 0.2508],
        [0.9870, 0.0130],
        [0.7221, 0.2779],
        [0.9477, 0.0523],
        [0.0167, 0.9833],
        [0.1072, 0.8928],
        [0.9599, 0.0401],
        [0.0218, 0.9782],
        [0.9425, 0.0575],
        [0.0200, 0.9800],
        [0.5003, 0.4997],
        [0.0122, 0.9878],
        [0.2621, 0.7379],
        [0.0172, 0.9828],
        [0.5647, 0.4353],
        [0.9721, 0.0279],
        [0.7472, 0.2528],
        [0.5225, 0.4775],
        [0.0925, 0.9075],
        [0.0419, 0.9581],
        [0.2924, 0.7076],
        [0.9180, 0.0820],
        [0.0109, 0.9891],
        [0.9967, 0.0033],
        [0.9511, 0.0489],
        [0.7673, 0.2327],
        [0.7883, 0.2117],
        [0.6169, 0.3831],
        [0.7869, 0.2131]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
      

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.9024, 0.0976],
        [0.0989, 0.9011],
        [0.0494, 0.9506],
        [0.1509, 0.8491],
        [0.1223, 0.8777],
        [0.9215, 0.0785],
        [0.6809, 0.3191],
        [0.9714, 0.0286],
        [0.4988, 0.5012],
        [0.9899, 0.0101],
        [0.0314, 0.9686],
        [0.8194, 0.1806],
        [0.1755, 0.8245],
        [0.0028, 0.9972],
        [0.1045, 0.8955],
        [0.4678, 0.5322],
        [0.7733, 0.2267],
        [0.0234, 0.9766],
        [0.1813, 0.8187],
        [0.6977, 0.3023],
        [0.9385, 0.0615],
        [0.9187, 0.0813],
        [0.8421, 0.1579],
        [0.9971, 0.0029],
        [0.0018, 0.9982],
        [0.4499, 0.5501],
        [0.0282, 0.9718],
        [0.3134, 0.6866],
        [0.8010, 0.1990],
        [0.3017, 0.6983],
        [0.1417, 0.8583],
        [0.0086, 0.9914]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
      

        [0.9550, 0.0450]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[9.1972e-01, 8.0284e-02],
        [9.2135e-01, 7.8649e-02],
        [3.3328e-01, 6.6672e-01],
        [7.1644e-01, 2.8356e-01],
        [3.5955e-02, 9.6405e-01],
        [8.0190e-01, 1.9810e-01],
        [9.3415e-01, 6.5846e-02],
        [9.3797e-01, 6.2029e-02],
        [1.1087e-01, 8.8913e-01],
        [8.7960e-01, 1.2040e-01],
        [8.6248e-01, 1.3752e-01],
      

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[1.7163e-01, 8.2837e-01],
        [9.6684e-01, 3.3160e-02],
        [3.3552e-01, 6.6448e-01],
        [7.6868e-01, 2.3132e-01],
        [8.7643e-01, 1.2357e-01],
        [9.5967e-01, 4.0327e-02],
        [7.1085e-01, 2.8915e-01],
        [6.0865e-01, 3.9135e-01],
        [2.3116e-03, 9.9769e-01],
        [4.1531e-02, 9.5847e-01],
        [8.6086e-01, 1.3914e-01],
        [3.3431e-01, 6.6569e-01],
        [9.3299e-01, 6.7009e-02],
        [5.4113e-01, 4.5887e-01],
        [9.3618e-01, 6.3823e-02],
        [9.9853e-01, 1.4654e-03],
        [3.6989e-02, 9.6301e-01],
        [9.9704e-01, 2.9598e-03],
        [9.7894e-01, 2.1060e-02],
        [9.5666e-01, 4.3336e-02],
        [4.9843e-03, 9.9502e-01],
        [1.9765e-04, 9.9980e-01],
        [8.3729e-01, 1.6271e-01],
        [6.8011e-01, 3.1989e-01],
        [7.0162e-01, 2.9838e-01],
        [6.5966e-01, 3.4034e-01],
        [9.7975e-01, 2.0246e-02],
        [9.6402e-01, 3.5980e-

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[1.2330e-02, 9.8767e-01],
        [7.1029e-02, 9.2897e-01],
        [2.5614e-01, 7.4386e-01],
        [8.8076e-01, 1.1924e-01],
        [2.1645e-03, 9.9784e-01],
        [3.1212e-01, 6.8788e-01],
        [5.4259e-03, 9.9457e-01],
        [2.4059e-02, 9.7594e-01],
        [7.9336e-04, 9.9921e-01],
        [7.1246e-01, 2.8754e-01],
        [3.9980e-01, 6.0020e-01],
        [8.1212e-01, 1.8788e-01],
        [9.7345e-01, 2.6548e-02],
        [7.7348e-01, 2.2652e-01],
        [2.1548e-02, 9.7845e-01],
        [9.6150e-02, 9.0385e-01],
        [1.8860e-02, 9.8114e-01],
        [5.1879e-01, 4.8121e-01],
        [9.6165e-01, 3.8346e-02],
        [9.8780e-01, 1.2203e-02],
        [6.9517e-02, 9.3048e-01],
        [8.0409e-01, 1.9591e-01],
        [7.4544e-01, 2.5456e-01],
        [9.1959e-01, 8.0410e-02],
        [6.3868e-01, 3.6132e-01],
        [6.1486e-01, 3.8514e-01],
        [6.4344e-02, 9.3566e-01],
        [1.9875e-01, 8.0125e-

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[9.0941e-01, 9.0588e-02],
        [1.7777e-01, 8.2223e-01],
        [9.2377e-01, 7.6227e-02],
        [3.0030e-01, 6.9970e-01],
        [9.4401e-01, 5.5994e-02],
        [9.5167e-02, 9.0483e-01],
        [7.6186e-01, 2.3814e-01],
        [8.0613e-01, 1.9387e-01],
        [1.4141e-01, 8.5859e-01],
        [5.1815e-01, 4.8185e-01],
        [2.5488e-01, 7.4512e-01],
        [5.6626e-01, 4.3374e-01],
        [9.3527e-01, 6.4726e-02],
        [5.6849e-01, 4.3151e-01],
        [9.1623e-01, 8.3770e-02],
        [5.1531e-01, 4.8469e-01],
        [7.3089e-01, 2.6911e-01],
        [9.4509e-01, 5.4911e-02],
        [3.8282e-02, 9.6172e-01],
        [9.0652e-01, 9.3483e-02],
        [1.1620e-01, 8.8380e-01],
        [1.5772e-01, 8.4228e-01],
        [9.9015e-01, 9.8532e-03],
        [6.8323e-01, 3.1677e-01],
        [9.9956e-01, 4.4025e-04],
        [6.5791e-01, 3.4209e-01],
        [3.5805e-03, 9.9642e-01],
        [4.5231e-01, 5.4769e-

        [0.3135, 0.6865]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[3.5234e-01, 6.4766e-01],
        [1.7918e-01, 8.2082e-01],
        [9.3526e-01, 6.4744e-02],
        [1.9910e-02, 9.8009e-01],
        [6.6280e-01, 3.3720e-01],
        [7.2650e-01, 2.7350e-01],
        [1.7452e-02, 9.8255e-01],
        [4.3942e-01, 5.6058e-01],
        [4.6482e-04, 9.9954e-01],
        [9.6984e-01, 3.0160e-02],
        [1.4167e-02, 9.8583e-01],
      

        [5.5148e-01, 4.4852e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[9.9976e-01, 2.4053e-04],
        [4.8150e-01, 5.1850e-01],
        [3.0557e-03, 9.9694e-01],
        [9.6489e-01, 3.5114e-02],
        [9.6603e-01, 3.3972e-02],
        [9.6872e-01, 3.1283e-02],
        [9.2522e-01, 7.4778e-02],
        [9.2583e-01, 7.4174e-02],
        [3.8677e-01, 6.1323e-01],
        [7.1783e-01, 2.8217e-01],
        [4.8686e-02, 9.5131e-01]

        [0.7361, 0.2639]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.9387, 0.0613],
        [0.9332, 0.0668],
        [0.0409, 0.9591],
        [0.3595, 0.6405],
        [0.0508, 0.9492],
        [0.0076, 0.9924],
        [0.0649, 0.9351],
        [0.2677, 0.7323],
        [0.9441, 0.0559],
        [0.5194, 0.4806],
        [0.9299, 0.0701],
        [0.1070, 0.8930],
        [0.7977, 0.2023],
        [0.0044, 0.9956],
        [0.0486,

        [0.4201, 0.5799]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.9600, 0.0400],
        [0.8422, 0.1578],
        [0.0424, 0.9576],
        [0.2016, 0.7984],
        [0.0026, 0.9974],
        [0.1348, 0.8652],
        [0.4062, 0.5938],
        [0.9725, 0.0275],
        [0.5392, 0.4608],
        [0.2763, 0.7237],
        [0.0209, 0.9791],
        [0.8551, 0.1449],
        [0.2335, 0.7665],
        [0.0743, 0.9257],
        [0.9775,

        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[9.1417e-01, 8.5827e-02],
        [7.2775e-02, 9.2722e-01],
        [9.7695e-01, 2.3052e-02],
        [9.5589e-01, 4.4107e-02],
        [7.3182e-04, 9.9927e-01],
        [4.3288e-01, 5.6712e-01],
        [4.4556e-01, 5.5444e-01],
        [9.4025e-01, 5.9751e-02],
        [7.5075e-01, 2.4925e-01],
        [8.8553e-01, 1.1447e-01],
        [2.2136e-01, 7.7864e-01],
        [9.6260e-01, 3.7404e-02],
        [9.9932e-01, 6.7660e-04],
        [2.8708e-03, 9.9713e-01],
        [8.8136e-02, 9.1186e-01],
        [2.2073e-03, 9.9779e-01],
        [9.7181e-01, 2.8187e-02],
        [1.4523e-01, 8.5477e-01],
        [1.3519e-01, 8.6481e-01],
        [8.1492e-01, 1.8508e-01],
        [2.2050e-01, 7.7951e-01],
        [1.2115e-01, 8.7885e-01],
        [3.8578e-01, 6.1422e-01],
        [5.3980e-01, 4.6020e-01],
        [9.7561e-01, 2.4394e-02],
        [3.7636e-02, 9.6236e-01],
        [5.2585e-01, 4.7415e-01],
        [8.5980e-02, 9.1402e-

        [0.9836, 0.0164]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[8.5213e-01, 1.4787e-01],
        [9.6644e-01, 3.3557e-02],
        [6.9010e-01, 3.0990e-01],
        [9.6591e-01, 3.4086e-02],
        [9.2861e-01, 7.1390e-02],
        [6.8084e-01, 3.1916e-01],
        [7.5853e-01, 2.4147e-01],
        [3.6723e-01, 6.3277e-01],
        [9.9137e-01, 8.6307e-03],
        [1.0243e-01, 8.9757e-01],
        [7.5406e-01, 2.4594e-01],
      

        [8.2344e-01, 1.7656e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.8871, 0.1129],
        [0.9366, 0.0634],
        [0.9884, 0.0116],
        [0.9457, 0.0543],
        [0.9970, 0.0030],
        [0.9065, 0.0935],
        [0.9286, 0.0714],
        [0.0827, 0.9173],
        [0.0853, 0.9147],
        [0.0787, 0.9213],
        [0.9154, 0.0846],
        [0.9958, 0.0042],
        [0.9401, 0.0599],
        [0.8938, 0.1062],
        

        [0.0251, 0.9749]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.9878, 0.0122],
        [0.5999, 0.4001],
        [0.0746, 0.9254],
        [0.8957, 0.1043],
        [0.9423, 0.0577],
        [0.2694, 0.7306],
        [0.8435, 0.1565],
        [0.9809, 0.0191],
        [0.2512, 0.7488],
        [0.2926, 0.7074],
        [0.8020, 0.1980],
        [0.9232, 0.0768],
        [0.3499, 0.6501],
        [0.0754, 0.9246],
        [0.5238,

        [0.0308, 0.9692]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.8698, 0.1302],
        [0.0384, 0.9616],
        [0.8835, 0.1165],
        [0.8859, 0.1141],
        [0.4373, 0.5627],
        [0.9814, 0.0186],
        [0.4418, 0.5582],
        [0.7492, 0.2508],
        [0.9293, 0.0707],
        [0.0376, 0.9624],
        [0.8777, 0.1223],
        [0.0363, 0.9637],
        [0.8843, 0.1157],
        [0.2714, 0.7286],
        [0.0043,

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[8.5880e-01, 1.4120e-01],
        [3.4558e-01, 6.5442e-01],
        [9.7017e-01, 2.9831e-02],
        [7.7415e-01, 2.2585e-01],
        [6.9413e-02, 9.3059e-01],
        [3.8508e-01, 6.1492e-01],
        [9.3402e-01, 6.5976e-02],
        [4.8205e-01, 5.1795e-01],
        [1.5422e-01, 8.4578e-01],
        [8.1153e-01, 1.8847e-01],
        [9.9616e-01, 3.8373e-03],
        [1.6807e-01, 8.3193e-01],
        [8.0401e-01, 1.9599e-01],
        [9.3631e-01, 6.3694e-02],
        [1.7153e-04, 9.9983e-01],
        [8.6934e-01, 1.3066e-01],
        [4.6168e-01, 5.3832e-01],
        [7.7555e-01, 2.2445e-01],
        [2.2477e-02, 9.7752e-01],
        [9.4856e-01, 5.1445e-02],
        [5.3362e-01, 4.6638e-01],
        [9.8803e-01, 1.1974e-02],
        [9.9848e-01, 1.5206e-03],
        [8.6815e-01, 1.3185e-01],
        [3.8466e-01, 6.1534e-01],
        [8.5708e-01, 1.4292e-01],
        [7.8775e-01, 2.1225e-01],
        [2.2553e-02, 9.7745e-

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[5.5695e-01, 4.4305e-01],
        [1.0358e-01, 8.9642e-01],
        [9.6474e-01, 3.5261e-02],
        [1.3588e-02, 9.8641e-01],
        [3.9392e-02, 9.6061e-01],
        [9.6696e-01, 3.3036e-02],
        [9.4279e-01, 5.7206e-02],
        [3.3713e-01, 6.6287e-01],
        [9.9782e-01, 2.1850e-03],
        [4.3169e-01, 5.6831e-01],
        [8.7421e-01, 1.2579e-01],
        [9.2637e-01, 7.3625e-02],
        [1.8758e-01, 8.1242e-01],
        [3.7398e-02, 9.6260e-01],
        [5.6690e-01, 4.3310e-01],
        [9.6818e-01, 3.1816e-02],
        [5.3898e-02, 9.4610e-01],
        [7.3287e-01, 2.6713e-01],
        [8.5516e-01, 1.4484e-01],
        [2.4863e-02, 9.7514e-01],
        [6.5593e-01, 3.4407e-01],
        [3.2062e-03, 9.9679e-01],
        [6.1327e-01, 3.8673e-01],
        [7.8514e-01, 2.1486e-01],
        [7.8373e-02, 9.2163e-01],
        [8.6128e-01, 1.3872e-01],
        [8.6889e-01, 1.3111e-01],
        [2.4694e-01, 7.5306e-

        [0.9538, 0.0462]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.1999, 0.8001],
        [0.3363, 0.6637],
        [0.1439, 0.8561],
        [0.9116, 0.0884],
        [0.2673, 0.7327],
        [0.9360, 0.0640],
        [0.6239, 0.3761],
        [0.2334, 0.7666],
        [0.0035, 0.9965],
        [0.0059, 0.9941],
        [0.0047, 0.9953],
        [0.9903, 0.0097],
        [0.0041, 0.9959],
        [0.9267, 0.0733],
        [0.6393,

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.3932, 0.6068],
        [0.9420, 0.0580],
        [0.0070, 0.9930],
        [0.0733, 0.9267],
        [0.0238, 0.9762],
        [0.3010, 0.6990],
        [0.2879, 0.7121],
        [0.9689, 0.0311],
        [0.9368, 0.0632],
        [0.8211, 0.1789],
        [0.0079, 0.9921],
        [0.9490, 0.0510],
        [0.9705, 0.0295],
        [0.0331, 0.9669],
        [0.8163, 0.1837],
        [0.0078, 0.9922],
        [0.9885, 0.0115],
        [0.3238, 0.6762],
        [0.1705, 0.8295],
        [0.3308, 0.6692],
        [0.0205, 0.9795],
        [0.0131, 0.9869],
        [0.1605, 0.8395],
        [0.5020, 0.4980],
        [0.9471, 0.0529],
        [0.1808, 0.8192],
        [0.0912, 0.9088],
        [0.9639, 0.0361],
        [0.1931, 0.8069],
        [0.0113, 0.9887],
        [0.8992, 0.1008],
        [0.0487, 0.9513]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
      

        [0.1535, 0.8465]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.4711, 0.5289],
        [0.1931, 0.8069],
        [0.0332, 0.9668],
        [0.6200, 0.3800],
        [0.0369, 0.9631],
        [0.9885, 0.0115],
        [0.9361, 0.0639],
        [0.0557, 0.9443],
        [0.9520, 0.0480],
        [0.2283, 0.7717],
        [0.1874, 0.8126],
        [0.0501, 0.9499],
        [0.1363, 0.8637],
        [0.9375, 0.0625],
        [0.0338,

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[9.7893e-03, 9.9021e-01],
        [9.8865e-01, 1.1353e-02],
        [9.8013e-01, 1.9871e-02],
        [9.4896e-01, 5.1042e-02],
        [3.8136e-01, 6.1864e-01],
        [8.0010e-01, 1.9990e-01],
        [9.3667e-01, 6.3326e-02],
        [2.5829e-01, 7.4171e-01],
        [1.1216e-01, 8.8784e-01],
        [8.5939e-01, 1.4061e-01],
        [5.1380e-01, 4.8620e-01],
        [9.6091e-01, 3.9094e-02],
        [2.2070e-02, 9.7793e-01],
        [9.8446e-01, 1.5536e-02],
        [2.3832e-02, 9.7617e-01],
        [4.0284e-02, 9.5972e-01],
        [1.3391e-04, 9.9987e-01],
        [9.8479e-01, 1.5208e-02],
        [8.9773e-01, 1.0227e-01],
        [4.5273e-01, 5.4727e-01],
        [9.2254e-01, 7.7457e-02],
        [3.7271e-01, 6.2729e-01],
        [1.8978e-02, 9.8102e-01],
        [9.9243e-01, 7.5665e-03],
        [9.9933e-01, 6.7264e-04],
        [9.3090e-01, 6.9100e-02],
        [9.9162e-01, 8.3808e-03],
        [9.6518e-01, 3.4817e-

        [2.1110e-01, 7.8890e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.9301, 0.0699],
        [0.0323, 0.9677],
        [0.9726, 0.0274],
        [0.1167, 0.8833],
        [0.0261, 0.9739],
        [0.7158, 0.2842],
        [0.7016, 0.2984],
        [0.9610, 0.0390],
        [0.3058, 0.6942],
        [0.0307, 0.9693],
        [0.0292, 0.9708],
        [0.8669, 0.1331],
        [0.7629, 0.2371],
        [0.9292, 0.0708],
        

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.7157, 0.2843],
        [0.9954, 0.0046],
        [0.8757, 0.1243],
        [0.0339, 0.9661],
        [0.9956, 0.0044],
        [0.7140, 0.2860],
        [0.5611, 0.4389],
        [0.8705, 0.1295],
        [0.2878, 0.7122],
        [0.6354, 0.3646],
        [0.2240, 0.7760],
        [0.9892, 0.0108],
        [0.1065, 0.8935],
        [0.8094, 0.1906],
        [0.8809, 0.1191],
        [0.3524, 0.6476],
        [0.3369, 0.6631],
        [0.4150, 0.5850],
        [0.6219, 0.3781],
        [0.0959, 0.9041],
        [0.6007, 0.3993],
        [0.0210, 0.9790],
        [0.3387, 0.6613],
        [0.9526, 0.0474],
        [0.0443, 0.9557],
        [0.0270, 0.9730],
        [0.2464, 0.7536],
        [0.0510, 0.9490],
        [0.3824, 0.6176],
        [0.0507, 0.9493],
        [0.0481, 0.9519],
        [0.9365, 0.0635]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
      

        [0.9836, 0.0164]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.8542, 0.1458],
        [0.1518, 0.8482],
        [0.0065, 0.9935],
        [0.7880, 0.2120],
        [0.5131, 0.4869],
        [0.6040, 0.3960],
        [0.0025, 0.9975],
        [0.2598, 0.7402],
        [0.8652, 0.1348],
        [0.9378, 0.0622],
        [0.0036, 0.9964],
        [0.9038, 0.0962],
        [0.7601, 0.2399],
        [0.2482, 0.7518],
        [0.7147,

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.9776, 0.0224],
        [0.5645, 0.4355],
        [0.0480, 0.9520],
        [0.8160, 0.1840],
        [0.9951, 0.0049],
        [0.1891, 0.8109],
        [0.9886, 0.0114],
        [0.1560, 0.8440],
        [0.9635, 0.0365],
        [0.9426, 0.0574],
        [0.0217, 0.9783],
        [0.1549, 0.8451],
        [0.9336, 0.0664],
        [0.0156, 0.9844],
        [0.8236, 0.1764],
        [0.0072, 0.9928],
        [0.0096, 0.9904],
        [0.0292, 0.9708],
        [0.8580, 0.1420],
        [0.7987, 0.2013],
        [0.2907, 0.7093],
        [0.3918, 0.6082],
        [0.8011, 0.1989],
        [0.0280, 0.9720],
        [0.9515, 0.0485],
        [0.3912, 0.6088],
        [0.5260, 0.4740],
        [0.9217, 0.0783],
        [0.1784, 0.8216],
        [0.0196, 0.9804],
        [0.9293, 0.0707],
        [0.9174, 0.0826]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
      

        [0.5459, 0.4541]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.3573, 0.6427],
        [0.8277, 0.1723],
        [0.6666, 0.3334],
        [0.0737, 0.9263],
        [0.9692, 0.0308],
        [0.6966, 0.3034],
        [0.6115, 0.3885],
        [0.0048, 0.9952],
        [0.1393, 0.8607],
        [0.0903, 0.9097],
        [0.9601, 0.0399],
        [0.1795, 0.8205],
        [0.0914, 0.9086],
        [0.5000, 0.5000],
        [0.8420,

        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.9731, 0.0269],
        [0.4094, 0.5906],
        [0.0292, 0.9708],
        [0.9977, 0.0023],
        [0.1544, 0.8456],
        [0.9533, 0.0467],
        [0.0322, 0.9678],
        [0.0736, 0.9264],
        [0.9213, 0.0787],
        [0.2211, 0.7789],
        [0.7232, 0.2768],
        [0.5616, 0.4384],
        [0.9833, 0.0167],
        [0.9130, 0.0870],
        [0.4311, 0.5689],
        [0.9727, 0.0273],
        [0.9684, 0.0316],
        [0.7167, 0.2833],
        [0.9910, 0.0090],
        [0.8664, 0.1336],
        [0.9696, 0.0304],
        [0.2351, 0.7649],
        [0.9841, 0.0159],
        [0.9981, 0.0019],
        [0.8046, 0.1954],
        [0.7986, 0.2014],
        [0.8960, 0.1040],
        [0.3873, 0.6127],
        [0.8492, 0.1508],
        [0.0192, 0.9808],
        [0.8968, 0.1032],
        [0.9414, 0.0586]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
      

        [0.6553, 0.3447]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[9.2513e-01, 7.4867e-02],
        [1.3526e-02, 9.8647e-01],
        [7.9189e-01, 2.0811e-01],
        [2.2103e-02, 9.7790e-01],
        [6.0374e-02, 9.3963e-01],
        [2.2570e-02, 9.7743e-01],
        [1.3351e-02, 9.8665e-01],
        [5.7913e-03, 9.9421e-01],
        [7.8020e-03, 9.9220e-01],
        [1.1218e-01, 8.8782e-01],
        [9.3513e-01, 6.4867e-02],
      

        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.5948, 0.4052],
        [0.9823, 0.0177],
        [0.9066, 0.0934],
        [0.0029, 0.9971],
        [0.9224, 0.0776],
        [0.0191, 0.9809],
        [0.0038, 0.9962],
        [0.9018, 0.0982],
        [0.5404, 0.4596],
        [0.9351, 0.0649],
        [0.8412, 0.1588],
        [0.0455, 0.9545],
        [0.9472, 0.0528],
        [0.0343, 0.9657],
        [0.8700, 0.1300],
        [0.9357, 0.0643],
        [0.0126, 0.9874],
        [0.6014, 0.3986],
        [0.3724, 0.6276],
        [0.4162, 0.5838],
        [0.9468, 0.0532],
        [0.2916, 0.7084],
        [0.9459, 0.0541],
        [0.1155, 0.8845],
        [0.9128, 0.0872],
        [0.9581, 0.0419],
        [0.8483, 0.1517],
        [0.9509, 0.0491],
        [0.6960, 0.3040],
        [0.9471, 0.0529],
        [0.8864, 0.1136],
        [0.5535, 0.4465]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
      

        [8.7759e-01, 1.2241e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.9854, 0.0146],
        [0.9700, 0.0300],
        [0.1343, 0.8657],
        [0.9766, 0.0234],
        [0.6813, 0.3187],
        [0.9149, 0.0851],
        [0.8027, 0.1973],
        [0.8952, 0.1048],
        [0.5290, 0.4710],
        [0.9129, 0.0871],
        [0.9914, 0.0086],
        [0.9757, 0.0243],
        [0.2886, 0.7114],
        [0.8690, 0.1310],
        

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[9.4607e-01, 5.3935e-02],
        [8.6524e-01, 1.3476e-01],
        [7.2547e-02, 9.2745e-01],
        [5.0290e-01, 4.9710e-01],
        [7.0872e-02, 9.2913e-01],
        [1.4475e-02, 9.8552e-01],
        [1.8478e-02, 9.8152e-01],
        [6.7116e-02, 9.3288e-01],
        [4.3982e-01, 5.6018e-01],
        [2.4492e-01, 7.5508e-01],
        [7.1886e-02, 9.2811e-01],
        [9.9572e-01, 4.2763e-03],
        [9.6836e-01, 3.1643e-02],
        [9.6060e-01, 3.9404e-02],
        [6.8580e-01, 3.1420e-01],
        [7.8542e-01, 2.1458e-01],
        [9.3595e-01, 6.4055e-02],
        [8.0163e-01, 1.9837e-01],
        [9.8688e-01, 1.3120e-02],
        [9.8346e-01, 1.6542e-02],
        [4.7692e-01, 5.2308e-01],
        [2.8979e-01, 7.1021e-01],
        [9.4789e-01, 5.2106e-02],
        [8.1927e-02, 9.1807e-01],
        [9.8276e-01, 1.7238e-02],
        [5.0810e-02, 9.4919e-01],
        [9.5684e-01, 4.3159e-02],
        [9.9920e-01, 8.0133e-

        [0.8693, 0.1307]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[1.5706e-02, 9.8429e-01],
        [8.4110e-01, 1.5890e-01],
        [8.5853e-01, 1.4147e-01],
        [9.9086e-01, 9.1364e-03],
        [2.4521e-01, 7.5479e-01],
        [6.0839e-01, 3.9161e-01],
        [5.8508e-04, 9.9941e-01],
        [3.4244e-01, 6.5756e-01],
        [9.6804e-01, 3.1964e-02],
        [9.4651e-01, 5.3488e-02],
        [9.0169e-01, 9.8305e-02],
      

        [0.9326, 0.0674]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.9563, 0.0437],
        [0.0411, 0.9589],
        [0.4826, 0.5174],
        [0.0214, 0.9786],
        [0.9990, 0.0010],
        [0.8134, 0.1866],
        [0.0135, 0.9865],
        [0.4592, 0.5408],
        [0.0295, 0.9705],
        [0.5457, 0.4543],
        [0.4794, 0.5206],
        [0.3410, 0.6590],
        [0.0322, 0.9678],
        [0.0389, 0.9611],
        [0.0175,

        [7.2557e-01, 2.7443e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.4028, 0.5972],
        [0.7863, 0.2137],
        [0.8060, 0.1940],
        [0.0944, 0.9056],
        [0.9842, 0.0158],
        [0.9978, 0.0022],
        [0.8453, 0.1547],
        [0.0235, 0.9765],
        [0.0020, 0.9980],
        [0.5563, 0.4437],
        [0.5735, 0.4265],
        [0.0438, 0.9562],
        [0.0342, 0.9658],
        [0.3682, 0.6318],
        

        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.8673, 0.1327],
        [0.4699, 0.5301],
        [0.9722, 0.0278],
        [0.5012, 0.4988],
        [0.0149, 0.9851],
        [0.0363, 0.9637],
        [0.0301, 0.9699],
        [0.9845, 0.0155],
        [0.9035, 0.0965],
        [0.0578, 0.9422],
        [0.0179, 0.9821],
        [0.9664, 0.0336],
        [0.9790, 0.0210],
        [0.6394, 0.3606],
        [0.9957, 0.0043],
        [0.9912, 0.0088],
        [0.5759, 0.4241],
        [0.9885, 0.0115],
        [0.9379, 0.0621],
        [0.2156, 0.7844],
        [0.0768, 0.9232],
        [0.6635, 0.3365],
        [0.9971, 0.0029],
        [0.0186, 0.9814],
        [0.0162, 0.9838],
        [0.0649, 0.9351],
        [0.3490, 0.6510],
        [0.3882, 0.6118],
        [0.0834, 0.9166],
        [0.2743, 0.7257],
        [0.4018, 0.5982],
        [0.0163, 0.9837]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
      

        [0.9100, 0.0900]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.0468, 0.9532],
        [0.8481, 0.1519],
        [0.0868, 0.9132],
        [0.9383, 0.0617],
        [0.0020, 0.9980],
        [0.9674, 0.0326],
        [0.9464, 0.0536],
        [0.9856, 0.0144],
        [0.0458, 0.9542],
        [0.4138, 0.5862],
        [0.0240, 0.9760],
        [0.5327, 0.4673],
        [0.9128, 0.0872],
        [0.9382, 0.0618],
        [0.9065,

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.9967, 0.0033],
        [0.1334, 0.8666],
        [0.8931, 0.1069],
        [0.0385, 0.9615],
        [0.9780, 0.0220],
        [0.8381, 0.1619],
        [0.0031, 0.9969],
        [0.9015, 0.0985],
        [0.0351, 0.9649],
        [0.0438, 0.9562],
        [0.0214, 0.9786],
        [0.2626, 0.7374],
        [0.0238, 0.9762],
        [0.5699, 0.4301],
        [0.4694, 0.5307],
        [0.7266, 0.2734],
        [0.0385, 0.9615],
        [0.8847, 0.1153],
        [0.8075, 0.1925],
        [0.7828, 0.2172],
        [0.4618, 0.5382],
        [0.9641, 0.0359],
        [0.9549, 0.0451],
        [0.9657, 0.0343],
        [0.1473, 0.8527],
        [0.9933, 0.0067],
        [0.9954, 0.0046],
        [0.4309, 0.5691],
        [0.5358, 0.4642],
        [0.8631, 0.1369],
        [0.8324, 0.1676],
        [0.9639, 0.0361]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
      

        [0.0618, 0.9382]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.9490, 0.0510],
        [0.7487, 0.2513],
        [0.9116, 0.0884],
        [0.0034, 0.9966],
        [0.0326, 0.9674],
        [0.8006, 0.1994],
        [0.5031, 0.4969],
        [0.9780, 0.0220],
        [0.1033, 0.8967],
        [0.9985, 0.0015],
        [0.1546, 0.8454],
        [0.3499, 0.6501],
        [0.9971, 0.0029],
        [0.8205, 0.1795],
        [0.4373,

        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.8379, 0.1621],
        [0.9789, 0.0211],
        [0.9211, 0.0789],
        [0.9543, 0.0457],
        [0.0425, 0.9575],
        [0.0017, 0.9983],
        [0.9980, 0.0020],
        [0.3779, 0.6221],
        [0.9669, 0.0331],
        [0.0198, 0.9802],
        [0.1884, 0.8116],
        [0.9476, 0.0524],
        [0.6313, 0.3687],
        [0.0223, 0.9777],
        [0.8782, 0.1218],
        [0.0078, 0.9922],
        [0.7349, 0.2651],
        [0.0060, 0.9940],
        [0.3899, 0.6101],
        [0.8708, 0.1292],
        [0.9910, 0.0090],
        [0.8389, 0.1611],
        [0.9676, 0.0324],
        [0.7576, 0.2424],
        [0.1586, 0.8414],
        [0.0212, 0.9788],
        [0.0061, 0.9939],
        [0.5640, 0.4360],
        [0.2747, 0.7253],
        [0.9166, 0.0834],
        [0.0537, 0.9463],
        [0.8969, 0.1031]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
      

        [0.2864, 0.7136]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.6022, 0.3978],
        [0.0089, 0.9911],
        [0.0200, 0.9800],
        [0.0122, 0.9878],
        [0.7300, 0.2700],
        [0.9079, 0.0921],
        [0.2130, 0.7870],
        [0.4775, 0.5225],
        [0.9917, 0.0083],
        [0.0918, 0.9082],
        [0.9972, 0.0028],
        [0.6170, 0.3830],
        [0.8197, 0.1803],
        [0.0918, 0.9082],
        [0.0425,

        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[1.0880e-01, 8.9120e-01],
        [1.6406e-01, 8.3594e-01],
        [9.5331e-01, 4.6693e-02],
        [9.1520e-01, 8.4802e-02],
        [4.2226e-01, 5.7774e-01],
        [4.0105e-01, 5.9895e-01],
        [9.6265e-01, 3.7354e-02],
        [3.4123e-01, 6.5877e-01],
        [8.9266e-01, 1.0734e-01],
        [2.6519e-01, 7.3481e-01],
        [1.6855e-02, 9.8315e-01],
        [1.5415e-02, 9.8458e-01],
        [1.2184e-01, 8.7816e-01],
        [9.7202e-01, 2.7976e-02],
        [9.8575e-01, 1.4249e-02],
        [8.4964e-02, 9.1504e-01],
        [5.2249e-02, 9.4775e-01],
        [8.0102e-01, 1.9898e-01],
        [1.8561e-02, 9.8144e-01],
        [4.7132e-01, 5.2868e-01],
        [7.7394e-01, 2.2606e-01],
        [6.9816e-02, 9.3018e-01],
        [9.9882e-01, 1.1790e-03],
        [2.9824e-03, 9.9702e-01],
        [9.5880e-01, 4.1200e-02],
        [9.4892e-01, 5.1083e-02],
        [7.8987e-04, 9.9921e-01],
        [2.2410e-02, 9.7759e-

        [6.5422e-01, 3.4578e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[1.1479e-03, 9.9885e-01],
        [9.9295e-01, 7.0536e-03],
        [9.3321e-01, 6.6792e-02],
        [8.1419e-01, 1.8581e-01],
        [2.0676e-01, 7.9324e-01],
        [9.4270e-01, 5.7303e-02],
        [9.4711e-01, 5.2888e-02],
        [7.1474e-01, 2.8526e-01],
        [4.3938e-01, 5.6062e-01],
        [9.7989e-01, 2.0109e-02],
        [9.8917e-01, 1.0832e-02]

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[1.1902e-01, 8.8098e-01],
        [1.8233e-01, 8.1767e-01],
        [2.2168e-02, 9.7783e-01],
        [9.9022e-01, 9.7803e-03],
        [9.9982e-01, 1.8010e-04],
        [2.3764e-02, 9.7624e-01],
        [4.0922e-01, 5.9078e-01],
        [1.4203e-01, 8.5797e-01],
        [2.3623e-01, 7.6377e-01],
        [8.8910e-04, 9.9911e-01],
        [8.9319e-01, 1.0681e-01],
        [1.6553e-01, 8.3447e-01],
        [3.5146e-01, 6.4854e-01],
        [9.9500e-01, 5.0038e-03],
        [3.3039e-03, 9.9670e-01],
        [7.5340e-01, 2.4660e-01],
        [9.7245e-01, 2.7553e-02],
        [2.8369e-03, 9.9716e-01],
        [9.9828e-01, 1.7236e-03],
        [9.5209e-01, 4.7913e-02],
        [5.2380e-01, 4.7620e-01],
        [1.5472e-01, 8.4528e-01],
        [9.7246e-01, 2.7541e-02],
        [9.9582e-01, 4.1751e-03],
        [9.8782e-01, 1.2178e-02],
        [4.9767e-01, 5.0233e-01],
        [5.1513e-01, 4.8487e-01],
        [5.4997e-01, 4.5003e-

        [0.7327, 0.2673]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.2246, 0.7754],
        [0.0818, 0.9182],
        [0.2443, 0.7557],
        [0.9547, 0.0453],
        [0.9568, 0.0432],
        [0.9484, 0.0516],
        [0.8346, 0.1654],
        [0.3009, 0.6991],
        [0.3999, 0.6001],
        [0.9094, 0.0906],
        [0.9108, 0.0892],
        [0.1061, 0.8939],
        [0.0392, 0.9608],
        [0.2353, 0.7647],
        [0.0120,

        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[9.8879e-01, 1.1207e-02],
        [9.0954e-01, 9.0456e-02],
        [9.7105e-01, 2.8955e-02],
        [2.2819e-02, 9.7718e-01],
        [8.3646e-01, 1.6354e-01],
        [3.4051e-04, 9.9966e-01],
        [6.6673e-02, 9.3333e-01],
        [1.1969e-01, 8.8031e-01],
        [9.9714e-01, 2.8639e-03],
        [8.5867e-01, 1.4133e-01],
        [9.6770e-01, 3.2304e-02],
        [6.2158e-01, 3.7842e-01],
        [1.4812e-02, 9.8519e-01],
        [9.5926e-01, 4.0744e-02],
        [7.9664e-01, 2.0336e-01],
        [8.6657e-01, 1.3343e-01],
        [9.9801e-01, 1.9867e-03],
        [5.4768e-02, 9.4523e-01],
        [1.6991e-01, 8.3009e-01],
        [9.9960e-01, 4.0355e-04],
        [9.7107e-01, 2.8929e-02],
        [8.3217e-01, 1.6783e-01],
        [9.6006e-01, 3.9938e-02],
        [9.9856e-03, 9.9001e-01],
        [6.1588e-02, 9.3841e-01],
        [4.1135e-03, 9.9589e-01],
        [7.4194e-02, 9.2581e-01],
        [9.4426e-01, 5.5738e-

        [8.7550e-01, 1.2450e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.0264, 0.9736],
        [0.9321, 0.0679],
        [0.0308, 0.9692],
        [0.0378, 0.9622],
        [0.9353, 0.0647],
        [0.9169, 0.0831],
        [0.7083, 0.2917],
        [0.1267, 0.8733],
        [0.9670, 0.0330],
        [0.0519, 0.9481],
        [0.7446, 0.2554],
        [0.4270, 0.5730],
        [0.6574, 0.3426],
        [0.9438, 0.0562],
        

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[2.7410e-01, 7.2590e-01],
        [4.4770e-01, 5.5230e-01],
        [2.7394e-02, 9.7261e-01],
        [9.5807e-01, 4.1930e-02],
        [8.8202e-01, 1.1798e-01],
        [4.4704e-01, 5.5296e-01],
        [7.9165e-01, 2.0835e-01],
        [9.4715e-01, 5.2848e-02],
        [7.0805e-01, 2.9195e-01],
        [8.9811e-01, 1.0189e-01],
        [1.0895e-01, 8.9105e-01],
        [9.1501e-01, 8.4994e-02],
        [3.0464e-03, 9.9695e-01],
        [7.0366e-01, 2.9634e-01],
        [9.9732e-01, 2.6821e-03],
        [4.3483e-03, 9.9565e-01],
        [9.6484e-01, 3.5160e-02],
        [9.4828e-01, 5.1719e-02],
        [8.6523e-01, 1.3477e-01],
        [8.6214e-01, 1.3786e-01],
        [9.8437e-01, 1.5629e-02],
        [8.5112e-01, 1.4888e-01],
        [4.0163e-03, 9.9598e-01],
        [1.9702e-04, 9.9980e-01],
        [9.6733e-01, 3.2666e-02],
        [4.8026e-01, 5.1974e-01],
        [9.7282e-01, 2.7177e-02],
        [5.1158e-01, 4.8842e-

        [9.7371e-01, 2.6290e-02]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[9.1772e-01, 8.2281e-02],
        [7.5859e-01, 2.4141e-01],
        [9.1356e-01, 8.6437e-02],
        [1.2773e-01, 8.7227e-01],
        [1.4299e-02, 9.8570e-01],
        [7.1401e-02, 9.2860e-01],
        [9.4602e-01, 5.3976e-02],
        [9.7306e-01, 2.6937e-02],
        [2.5154e-01, 7.4846e-01],
        [4.1847e-01, 5.8153e-01],
        [9.3615e-01, 6.3848e-02]

        [1, 0]], device='cuda:0', dtype=torch.int32)
tensor([[0.0288, 0.9712],
        [0.8766, 0.1234],
        [0.8312, 0.1688],
        [0.9343, 0.0657],
        [0.5921, 0.4079],
        [0.6937, 0.3063],
        [0.2143, 0.7857],
        [0.7627, 0.2373],
        [0.3518, 0.6482],
        [0.9779, 0.0221],
        [0.2912, 0.7088],
        [0.2344, 0.7656],
        [0.0823, 0.9177],
        [0.8428, 0.1572],
        [0.8809, 0.1191],
        [0.9753, 0.0247],
        [0.8353, 0.1647],
        [0.9291, 0.0709],
        [0.1047, 0.8953],
        [0.2656, 0.7344],
        [0.1435, 0.8565],
        [0.2604, 0.7396],
        [0.9670, 0.0330],
        [0.9009, 0.0991],
        [0.7863, 0.2137],
        [0.8695, 0.1305],
        [0.9585, 0.0415],
        [0.8916, 0.1084],
        [0.0594, 0.9406],
        [0.0575, 0.9425],
        [0.8149, 0.1851],
        [0.9601, 0.0399]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
      

        [0.5775, 0.4225]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.0882, 0.9118],
        [0.0060, 0.9940],
        [0.1794, 0.8206],
        [0.1750, 0.8250],
        [0.4268, 0.5732],
        [0.1657, 0.8343],
        [0.1866, 0.8134],
        [0.5366, 0.4634],
        [0.2827, 0.7173],
        [0.9159, 0.0841],
        [0.8568, 0.1432],
        [0.0315, 0.9685],
        [0.9692, 0.0308],
        [0.9861, 0.0139],
        [0.5467,

        [4.3082e-02, 9.5692e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[9.4016e-01, 5.9836e-02],
        [9.8523e-01, 1.4766e-02],
        [9.4928e-01, 5.0718e-02],
        [9.4018e-01, 5.9817e-02],
        [2.3710e-01, 7.6290e-01],
        [8.2850e-01, 1.7150e-01],
        [3.7452e-01, 6.2548e-01],
        [9.6202e-01, 3.7977e-02],
        [9.1142e-01, 8.8578e-02],
        [7.3383e-02, 9.2662e-01],
        [2.8281e-01, 7.1719e-01]

        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.6861, 0.3139],
        [0.1792, 0.8208],
        [0.1172, 0.8828],
        [0.0580, 0.9420],
        [0.0510, 0.9490],
        [0.8729, 0.1271],
        [0.0994, 0.9006],
        [0.5159, 0.4841],
        [0.0511, 0.9489],
        [0.9872, 0.0128],
        [0.4601, 0.5399],
        [0.7327, 0.2673],
        [0.7306, 0.2694],
        [0.8521, 0.1479],
        [0.9287, 0.0713],
        [0.8679, 0.1321],
        [0.0602, 0.9398],
        [0.6661, 0.3339],
        [0.0278, 0.9722],
        [0.1629, 0.8371],
        [0.9226, 0.0774],
        [0.0395, 0.9605],
        [0.9415, 0.0585],
        [0.9331, 0.0669],
        [0.0090, 0.9910],
        [0.9309, 0.0691],
        [0.0621, 0.9379],
        [0.9010, 0.0990],
        [0.1293, 0.8707],
        [0.8423, 0.1577],
        [0.9768, 0.0232],
        [0.0084, 0.9916]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
      

        [7.2944e-01, 2.7056e-01]], device='cuda:0', grad_fn=<SoftmaxBackward>) tensor([[0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1]], device='cuda:0', dtype=torch.int32)
tensor([[0.2387, 0.7613],
        [0.7423, 0.2577],
        [0.0816, 0.9184],
        [0.7352, 0.2648],
        [0.9772, 0.0228],
        [0.9065, 0.0935],
        [0.6004, 0.3996],
        [0.0162, 0.9838],
        [0.6145, 0.3855],
        [0.0486, 0.9514],
        [0.1649, 0.8351],
        [0.9309, 0.0691],
        [0.9988, 0.0012],
        [0.4380, 0.5620],
        

In [133]:
model.cpu()
def predict(index, model, tfidf):
    title = pos_sent['title'].iloc[index]
    content = pos_sent['content'].iloc[index]
    
    a = tfidf.transform([title])
    b = tfidf.transform([content])
    sim = phrase_cbow(a,b)
    a_vec = get_vectors(title)
    b_vec = get_vectors(content)
    
    feature = np.hstack((np.asarray(a_vec), sim, np.asarray(b_vec)))
    output = model(torch.tensor(feature).float())
    _, pred = torch.max(output, 1)
    
    print(f"Title: {title}")
    print(f"Content: \n{content}\n")
    
    if pred == 1:
        prediction = "Positive review"
    else:
        prediction = "Negative review"
        
    if df['sentiment'].iloc[index] == 1:
        truth = "Positive review"
    else:
        truth = "Negative review"
        
    print(f"Prediciton:\t{prediction}\nGround Truth:\t{truth}")
    print(f"Model is {'correct' if prediction == truth else 'incorrect'}.")

In [134]:
predict(a, model, tfidf)

Title: Great for Family
Content: 
This game is great for introducing kids to more interesting board games after they've already learned how to take turns. I can play with my 4 and 6 year old and not get bored, though towards the end of the game sometimes they will. Reducing the number of pawns and letting one start helps shorten the game. The pieces, board, and box are well made. It is good to have the kids understand counting, the strategy of which pawns to move, and also that they shouldn't get upset when they are bumped back (because they'll be able to do it to someone else too).

Prediciton:	Negative review
Ground Truth:	Positive review
Model is incorrect.
